db.createCollection("base_datos_empleados");
db.base_datos_empleados.insertMany(
  [
  {
    "nombres": "Maria",
    "apellidos": "Garcia",
    "correo": "maria.garcia@example.com",
    "ciudad": "Madrid",
    "pais": "Spain",
    "salario": 35000,
    "edad": 30,
    "altura": 165,
    "peso": 150
  },
  {
    "nombres": "John",
    "apellidos": "Smith",
    "correo": "john.smith@example.com",
    "ciudad": "New York City",
    "pais": "USA",
    "salario": 40000,
    "edad": 35,
    "altura": 180,
    "peso": 180
  },
  {
    "nombres": "Emily",
    "apellidos": "Johnson",
    "correo": "emily.johnson@example.com",
    "ciudad": "Los Angeles",
    "pais": "USA",
    "salario": 45000,
    "edad": 28,
    "altura": 160,
    "peso": 130
  },
  {
    "nombres": "Carlos",
    "apellidos": "Martinez",
    "correo": "carlos.martinez@example.com",
    "ciudad": "Buenos Aires",
    "pais": "Argentina",
    "salario": 38000,
    "edad": 32,
    "altura": 175,
    "peso": 170
  },
  {
    "nombres": "Laura",
    "apellidos": "Rodriguez",
    "correo": "laura.rodriguez@example.com",
    "ciudad": "Mexico City",
    "pais": "Mexico",
    "salario": 32000,
    "edad": 27,
    "altura": 155,
    "peso": 140
  },
  {
    "nombres": "David",
    "apellidos": "Gonzalez",
    "correo": "spam.gonzalez@example.com",
    "ciudad": "Santiago",
    "pais": "Chile",
    "salario": 42000,
    "edad": 33,
    "altura": 185,
    "peso": 190
  },
  {
    "nombres": "Sofia",
    "apellidos": "Brown",
    "correo": "sofia.brown@example.com",
    "ciudad": "Chicago",
    "pais": "USA",
    "salario": 37000,
    "edad": 29,
    "altura": 162,
    "peso": 135
  },
  {
    "nombres": "Michael",
    "apellidos": "Lopez",
    "correo": "michael.lopez@example.com",
    "ciudad": "Miami",
    "pais": "USA",
    "salario": 48000,
    "edad": 31,
    "altura": 178,
    "peso": 175
  },
  {
    "nombres": "Ana",
    "apellidos": "Silva",
    "correo": "ana.silva@example.com",
    "ciudad": "Rio de Janeiro",
    "pais": "Brazil",
    "salario": 34000,
    "edad": 26,
    "altura": 168,
    "peso": 155
  },
  {
    "nombres": "Sarah",
    "apellidos": "Wilson",
    "correo": "sarah.spam@example.com",
    "ciudad": "Toronto",
    "pais": "Canada",
    "salario": 41000,
    "edad": 34,
    "altura": 172,
    "peso": 150
  },
  {
    "nombres": "Javier",
    "apellidos": "Hernandez",
    "correo": "javier.hernandez@example.com",
    "ciudad": "Barcelona",
    "pais": "Spain",
    "salario": 39000,
    "edad": 30,
    "altura": 180,
    "peso": 170
  },
  {
    "nombres": "Emma",
    "apellidos": "Davis",
    "correo": "emma.davis@example.com",
    "ciudad": "Sydney",
    "pais": "Australia",
    "salario": 43000,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Diego",
    "apellidos": "Ramirez",
    "correo": "diego.ramirez@example.com",
    "ciudad": "Lima",
    "pais": "Peru",
    "salario": 36000,
    "edad": 28,
    "altura": 175,
    "peso": 160
  },
  {
    "nombres": "Jessica",
    "apellidos": "Taylor",
    "correo": "jessica.taylor@example.com",
    "ciudad": "London",
    "pais": "UK",
    "salario": 47000,
    "edad": 33,
    "altura": 167,
    "peso": 140
  },
  {
    "nombres": "Pedro",
    "apellidos": "Santos",
    "correo": "pedro.santos@example.com",
    "ciudad": "Lisbon",
    "pais": "Portugal",
    "salario": 35000,
    "edad": 29,
    "altura": 170,
    "peso": 155
  },
  {
    "nombres": "Rachel",
    "apellidos": "Lee",
    "correo": "rachel.lee@example.com",
    "ciudad": "Seoul",
    "pais": "South Korea",
    "salario": 44000,
    "edad": 31,
    "altura": 160,
    "peso": 135
  },
  {
    "nombres": "Lucas",
    "apellidos": "Fernandez",
    "correo": "lucas.fernandez@spam.com",
    "ciudad": "Buenos Aires",
    "pais": "Argentina",
    "salario": 40000,
    "edad": 27,
    "altura": 175,
    "peso": 180
  },
  {
    "nombres": "Olivia",
    "apellidos": "Brown",
    "correo": "olivia.brown@example.com",
    "ciudad": "Melbourne",
    "pais": "Australia",
    "salario": 46000,
    "edad": 30,
    "altura": 165,
    "peso": 145
  },
 {
    "nombres": "Sophia",
    "apellidos": "Andersen",
    "correo": "sophia.andersen@example.com",
    "ciudad": "Copenhagen",
    "pais": "Denmark",
    "salario": 48000,
    "edad": 29,
    "altura": 167,
    "peso": 135
  },
  {
    "nombres": "Lukas",
    "apellidos": "Schmidt",
    "correo": "lukas.spam@example.com",
    "ciudad": "Berlin",
    "pais": "Germany",
    "salario": 43000,
    "edad": 33,
    "altura": 178,
    "peso": 170
  },
  {
    "nombres": "Alessia",
    "apellidos": "Ricci",
    "correo": "alessia.ricci@example.com",
    "ciudad": "Rome",
    "pais": "Italy",
    "salario": 39000,
    "edad": 30,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Pablo",
    "apellidos": "González",
    "correo": "pablo.gonzalez@example.com",
    "ciudad": "Madrid",
    "pais": "Spain",
    "salario": 42000,
    "edad": 31,
    "altura": 180,
    "peso": 170
  },
  {
    "nombres": "Emma",
    "apellidos": "Lindberg",
    "correo": "emma.lindberg@example.com",
    "ciudad": "Stockholm",
    "pais": "Sweden",
    "salario": 40000,
    "edad": 27,
    "altura": 175,
    "peso": 180
  },
  {
    "nombres": "Niklas",
    "apellidos": "Andersson",
    "correo": "niklas.andersson@example.com",
    "ciudad": "Oslo",
    "pais": "Norway",
    "salario": 45000,
    "edad": 30,
    "altura": 165,
    "peso": 145
  },
  {
    "nombres": "Laura",
    "apellidos": "Martínez",
    "correo": "laura.martinez@example.spam",
    "ciudad": "Barcelona",
    "pais": "Spain",
    "salario": 37000,
    "edad": 29,
    "altura": 162,
    "peso": 135
  },
  {
    "nombres": "Liam",
    "apellidos": "Smith",
    "correo": "liam.smith@example.com",
    "ciudad": "London",
    "pais": "UK",
    "salario": 46000,
    "edad": 31,
    "altura": 167,
    "peso": 140
  },
  {
    "nombres": "Hanna",
    "apellidos": "Nielsen",
    "correo": "hanna.nielsen@example.com",
    "ciudad": "Copenhagen",
    "pais": "Denmark",
    "salario": 43000,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Maximilian",
    "apellidos": "Müller",
    "correo": "maximilian.muller@example.com",
    "ciudad": "Berlin",
    "pais": "Germany",
    "salario": 39000,
    "edad": 30,
    "altura": 180,
    "peso": 175
  },
  {
    "nombres": "Giulia",
    "apellidos": "Rossi",
    "correo": "giulia.rossi@example.com",
    "ciudad": "Rome",
    "pais": "Italy",
    "salario": 42000,
    "edad": 31,
    "altura": 160,
    "peso": 130
  },
  {
    "nombres": "Santiago",
    "apellidos": "López",
    "correo": "santiago.lopez@example.com",
    "ciudad": "Madrid",
    "pais": "Spain",
    "salario": 38000,
    "edad": 32,
    "altura": 175,
    "peso": 170
  },
  {
    "nombres": "Elsa",
    "apellidos": "Andersson",
    "correo": "elsa.andersson@example.com",
    "ciudad": "Stockholm",
    "pais": "Sweden",
    "salario": 40000,
    "edad": 27,
    "altura": 175,
    "peso": 180
  },
  {
    "nombres": "Oskar",
    "apellidos": "Berg",
    "correo": "oskar.berg@example.com",
    "ciudad": "Oslo",
    "pais": "Norway",
    "salario": 45000,
    "edad": 30,
    "altura": 165,
    "peso": 145
  },
  {
    "nombres": "Elena",
    "apellidos": "García",
    "correo": "elena.garcia@example.com",
    "ciudad": "Barcelona",
    "pais": "Spain",
    "salario": 37000,
    "edad": 29,
    "altura": 162,
    "peso": 135
  },
  {
    "nombres": "James",
    "apellidos": "Johnson",
    "correo": "james.johnson@example.com",
    "ciudad": "London",
    "pais": "UK",
    "salario": 46000,
    "edad": 31,
    "altura": 167,
    "peso": 140
  },
  {
    "nombres": "Freja",
    "apellidos": "Nielsen",
    "correo": "freja.nielsen@example.com",
    "ciudad": "Copenhagen",
    "pais": "Denmark",
    "salario": 43000,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Lukas",
    "apellidos": "Schneider",
    "correo": "lukas.schneider@example.com",
    "ciudad": "Berlin",
    "pais": "Germany",
    "salario": 39000,
    "edad": 30,
    "altura": 180,
    "peso": 175
  },
  {
    "nombres": "Chiara",
    "apellidos": "Russo",
    "correo": "chiara.russo@example.com",
    "ciudad": "Rome",
    "pais": "Italy",
    "salario": 42000,
    "edad": 31,
    "altura": 160,
    "peso": 130
  },
  {
    "nombres": "Mateo",
    "apellidos": "Gómez",
    "correo": "mateo.gomez@example.com",
    "ciudad": "Madrid",
    "pais": "Spain",
    "salario": 38000,
    "edad": 32,
    "altura": 175,
    "peso": 170
  },
  {
    "nombres": "Filippa",
    "apellidos": "Andersson",
    "correo": "filippa.andersson@example.com",
    "ciudad": "Stockholm",
    "pais": "Sweden",
    "salario": 40000,
    "edad": 27,
    "altura": 175,
    "peso": 180
  },
  {
    "nombres": "Marius",
    "apellidos": "Berg",
    "correo": "marius.berg@example.com",
    "ciudad": "Oslo",
    "pais": "Norway",
    "salario": 45000,
    "edad": 30,
    "altura": 165,
    "peso": 145
  },
  {
    "nombres": "Sara",
    "apellidos": "García",
    "correo": "sara.garcia@example.com",
    "ciudad": "Barcelona",
    "pais": "Spain",
    "salario": 37000,
    "edad": 29,
    "altura": 162,
    "peso": 135
  },
  {
    "nombres": "Jack",
    "apellidos": "Johnson",
    "correo": "jack.johnson@example.com",
    "ciudad": "London",
    "pais": "UK",
    "salario": 46000,
    "edad": 31,
    "altura": 167,
    "peso": 140
  },
  {
    "nombres": "Viggo",
    "apellidos": "Nielsen",
    "correo": "viggo.nielsen@example.com",
    "ciudad": "Copenhagen",
    "pais": "Denmark",
    "salario": 43000,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Finn",
    "apellidos": "Schulz",
    "correo": "finn.schulz@example.com",
    "ciudad": "Berlin",
    "pais": "Germany",
    "salario": 39000,
    "edad": 30,
    "altura": 180,
    "peso": 175
  },
  {
    "nombres": "Chiara",
    "apellidos": "Romano",
    "correo": "chiara.romano@example.com",
    "ciudad": "Rome",
    "pais": "Italy",
    "salario": 42000,
    "edad": 31,
    "altura": 160,
    "peso": 130
  },
  {
    "nombres": "Ismael",
    "apellidos": "Gutiérrez",
    "correo": "ismael.gutierrez@example.com",
    "ciudad": "Madrid",
    "pais": "Spain",
    "salario": 38000,
    "edad": 32,
    "altura": 175,
    "peso": 170
  },
  {
    "nombres": "Alice",
    "apellidos": "Johansson",
    "correo": "alice.johansson@example.com",
    "ciudad": "Stockholm",
    "pais": "Sweden",
    "salario": 40000,
    "edad": 27,
    "altura": 175,
    "peso": 180
  },
  {
    "nombres": "Oscar",
    "apellidos": "Berg",
    "correo": "oscar.berg@example.com",
    "ciudad": "Oslo",
    "pais": "Norway",
    "salario": 45000,
    "edad": 30,
    "altura": 165,
    "peso": 145
  },
  {
    "nombres": "Elena",
    "apellidos": "García",
    "correo": "elena.garcia@example.com",
    "ciudad": "Barcelona",
    "pais": "Spain",
    "salario": 37000,
    "edad": 29,
    "altura": 162,
    "peso": 135
  },
  {
    "nombres": "Noah",
    "apellidos": "Jensen",
    "correo": "noah.jensen@example.com",
    "ciudad": "Copenhagen",
    "pais": "Denmark",
    "salario": 43000,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Paul",
    "apellidos": "Schneider",
    "correo": "paul.schneider@example.com",
    "ciudad": "Berlin",
    "pais": "Germany",
    "salario": 39000,
    "edad": 30,
    "altura": 180,
    "peso": 175
  },
  {
    "nombres": "Lorenzo",
    "apellidos": "Ricci",
    "correo": "lorenzo.ricci@example.com",
    "ciudad": "Rome",
    "pais": "Italy",
    "salario": 42000,
    "edad": 31,
    "altura": 160,
    "peso": 130
  },
  {
    "nombres": "Marta",
    "apellidos": "Gómez",
    "correo": "marta.gomez@example.com",
    "ciudad": "Madrid",
    "pais": "Spain",
    "salario": 38000,
    "edad": 32,
    "altura": 175,
    "peso": 170
  },
  {
    "nombres": "Oliver",
    "apellidos": "Johansson",
    "correo": "oliver.johansson@example.com",
    "ciudad": "Stockholm",
    "pais": "Sweden",
    "salario": 40000,
    "edad": 27,
    "altura": 175,
    "peso": 180
  },
  {
    "nombres": "Liam",
    "apellidos": "Berg",
    "correo": "liam.berg@example.com",
    "ciudad": "Oslo",
    "pais": "Norway",
    "salario": 45000,
    "edad": 30,
    "altura": 165,
    "peso": 145
  },
  {
    "nombres": "Lucía",
    "apellidos": "García",
    "correo": "lucia.garcia@example.com",
    "ciudad": "Barcelona",
    "pais": "Spain",
    "salario": 37000,
    "edad": 29,
    "altura": 162,
    "peso": 135
  },
  {
    "nombres": "Harry",
    "apellidos": "Johnson",
    "correo": "harry.johnson@example.com",
    "ciudad": "London",
    "pais": "UK",
    "salario": 46000,
    "edad": 31,
    "altura": 167,
    "peso": 140
  },
  {
    "nombres": "Mathilde",
    "apellidos": "Nielsen",
    "correo": "mathilde.nielsen@example.com",
    "ciudad": "Copenhagen",
    "pais": "Denmark",
    "salario": 43000,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Lorenzo",
    "apellidos": "Romano",
    "correo": "lorenzo.romano@example.com",
    "ciudad": "Rome",
    "pais": "Italy",
    "salario": 42000,
    "edad": 31,
    "altura": 160,
    "peso": 130
  },
  {
    "nombres": "Elena",
    "apellidos": "Gutiérrez",
    "correo": "elena.gutierrez@example.com",
    "ciudad": "Madrid",
    "pais": "Spain",
    "salario": 38000,
    "edad": 32,
    "altura": 175,
    "peso": 170
  },
  {
    "nombres": "Alice",
    "apellidos": "Jensen",
    "correo": "alice.jensen@example.com",
    "ciudad": "Copenhagen",
    "pais": "Denmark",
    "salario": 43000,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Oscar",
    "apellidos": "Schneider",
    "correo": "oscar.schneider@example.com",
    "ciudad": "Berlin",
    "pais": "Germany",
    "salario": 39000,
    "edad": 30,
    "altura": 180,
    "peso": 175
  },
  {
    "nombres": "Oliver",
    "apellidos": "Ricci",
    "correo": "oliver.ricci@example.com",
    "ciudad": "Rome",
    "pais": "Italy",
    "salario": 42000,
    "edad": 31,
    "altura": 160,
    "peso": 130
  },
  {
    "nombres": "Lucas",
    "apellidos": "Gómez",
    "correo": "lucas.gomez@example.com",
    "ciudad": "Madrid",
    "pais": "Spain",
    "salario": 38000,
    "edad": 32,
    "altura": 175,
    "peso": 170
  },
  {
    "nombres": "Emma",
    "apellidos": "Johansson",
    "correo": "emma.johansson@example.com",
    "ciudad": "Stockholm",
    "pais": "Sweden",
    "salario": 40000,
    "edad": 27,
    "altura": 175,
    "peso": 180
  },
  {
    "nombres": "Marius",
    "apellidos": "Berg",
    "correo": "marius.berg@example.com",
    "ciudad": "Oslo",
    "pais": "Norway",
    "salario": 45000,
    "edad": 30,
    "altura": 165,
    "peso": 145
  },
  {
    "nombres": "Sara",
    "apellidos": "García",
    "correo": "sara.garcia@example.com",
    "ciudad": "Barcelona",
    "pais": "Spain",
    "salario": 37000,
    "edad": 29,
    "altura": 162,
    "peso": 135
  },
  {
    "nombres": "Jack",
    "apellidos": "Johnson",
    "correo": "jack.johnson@example.com",
    "ciudad": "London",
    "pais": "UK",
    "salario": 46000,
    "edad": 31,
    "altura": 167,
    "peso": 140
  },
  {
    "nombres": "Viggo",
    "apellidos": "Nielsen",
    "correo": "viggo.nielsen@example.com",
    "ciudad": "Copenhagen",
    "pais": "Denmark",
    "salario": 43000,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Finn",
    "apellidos": "Schulz",
    "correo": "finn.schulz@example.com",
    "ciudad": "Berlin",
    "pais": "Germany",
    "salario": 39000,
    "edad": 30,
    "altura": 180,
    "peso": 175
  },
  {
    "nombres": "Chiara",
    "apellidos": "Romano",
    "correo": "chiara.romano@example.com",
    "ciudad": "Rome",
    "pais": "Italy",
    "salario": 42000,
    "edad": 31,
    "altura": 160,
    "peso": 130
  },
  {
    "nombres": "Ismael",
    "apellidos": "Gutiérrez",
    "correo": "ismael.gutierrez@example.com",
    "ciudad": "Madrid",
    "pais": "Spain",
    "salario": 38000,
    "edad": 32,
    "altura": 175,
    "peso": 170
  },
  {
    "nombres": "Alice",
    "apellidos": "Johansson",
    "correo": "alice.johansson@example.com",
    "ciudad": "Stockholm",
    "pais": "Sweden",
    "salario": 40000,
    "edad": 27,
    "altura": 175,
    "peso": 180
  },
  {
    "nombres": "Oscar",
    "apellidos": "Berg",
    "correo": "oscar.berg@example.com",
    "ciudad": "Oslo",
    "pais": "Norway",
    "salario": 45000,
    "edad": 30,
    "altura": 165,
    "peso": 145
  },
  {
    "nombres": "Elena",
    "apellidos": "García",
    "correo": "elena.garcia@example.com",
    "ciudad": "Barcelona",
    "pais": "Spain",
    "salario": 37000,
    "edad": 29,
    "altura": 162,
    "peso": 135
  },
  {
    "nombres": "James",
    "apellidos": "Johnson",
    "correo": "james.johnson@example.com",
    "ciudad": "London",
    "pais": "UK",
    "salario": 46000,
    "edad": 31,
    "altura": 167,
    "peso": 140
  },
    {
    "nombres": "Emma",
    "apellidos": "Schneider",
    "correo": "emma.schneider@example.com",
    "ciudad": "Berlin",
    "pais": "Germany",
    "salario": 39000,
    "edad": 30,
    "altura": 180,
    "peso": 175
  },
  {
    "nombres": "Matteo",
    "apellidos": "Romano",
    "correo": "matteo.romano@example.com",
    "ciudad": "Rome",
    "pais": "Italy",
    "salario": 42000,
    "edad": 31,
    "altura": 160,
    "peso": 130
  },
  {
    "nombres": "Lucía",
    "apellidos": "Gutiérrez",
    "correo": "lucia.gutierrez@example.com",
    "ciudad": "Madrid",
    "pais": "Spain",
    "salario": 38000,
    "edad": 32,
    "altura": 175,
    "peso": 170
  },
  {
    "nombres": "Oscar",
    "apellidos": "Jensen",
    "correo": "oscar.jensen@example.com",
    "ciudad": "Copenhagen",
    "pais": "Denmark",
    "salario": 43000,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Lena",
    "apellidos": "Schulz",
    "correo": "lena.schulz@example.com",
    "ciudad": "Berlin",
    "pais": "Germany",
    "salario": 0,
    "edad": 30,
    "altura": 180,
    "peso": 175
  },
  {
    "nombres": "Alessandro",
    "apellidos": "Moretti",
    "correo": "alessandro.moretti@example.com",
    "ciudad": "Rome",
    "pais": "Italy",
    "salario": 42000,
    "edad": 31,
    "altura": 160,
    "peso": 130
  },
  {
    "nombres": "Sara",
    "apellidos": "Gómez",
    "correo": "sara.gomez@example.com",
    "ciudad": "Madrid",
    "pais": "Spain",
    "salario": 38000,
    "edad": 32,
    "altura": 175,
    "peso": 170
  },
  {
    "nombres": "Oliver",
    "apellidos": "Johannessen",
    "correo": "oliver.johannessen@example.com",
    "ciudad": "Oslo",
    "pais": "Norway",
    "salario": 45000,
    "edad": 30,
    "altura": 165,
    "peso": 145
  },
  {
    "nombres": "Hannah",
    "apellidos": "Andersen",
    "correo": "hannah.andersen@example.com",
    "ciudad": "Bello",
    "pais": "Denmark",
    "salario": 43000,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Mika",
    "apellidos": "Schulz",
    "correo": "mika.schulz@example.com",
    "ciudad": "Berlin",
    "pais": "Germany",
    "salario": 39000,
    "edad": 30,
    "altura": 180,
    "peso": 175
  },
  {
    "nombres": "Elisa",
    "apellidos": "Bianchi",
    "correo": "elisa.bianchi@example.com",
    "ciudad": "Rome",
    "pais": "Italy",
    "salario": 42000,
    "edad": 31,
    "altura": 160,
    "peso": 130
  },
  {
    "nombres": "Carlos",
    "apellidos": "Hernández",
    "correo": "carlos.hernandez@example.com",
    "ciudad": "Madrid",
    "pais": "Spain",
    "salario": 38000,
    "edad": 32,
    "altura": 175,
    "peso": 170
  },
  {
    "nombres": "Freja",
    "apellidos": "Jensen",
    "correo": "freja.jensen@example.com",
    "ciudad": "Copenhagen",
    "pais": "Denmark",
    "salario": 0,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Finn",
    "apellidos": "Meyer",
    "correo": "finn.meyer@example.com",
    "ciudad": "Berlin",
    "pais": "Germany",
    "salario": 39000,
    "edad": 30,
    "altura": 180,
    "peso": 175
  },
  {
    "nombres": "Giulia",
    "apellidos": "Conti",
    "correo": "giulia.conti@example.com",
    "ciudad": "Rome",
    "pais": "Italy",
    "salario": 42000,
    "edad": 31,
    "altura": 160,
    "peso": 130
  },
  {
    "nombres": "Alejandro",
    "apellidos": "Sánchez",
    "correo": "alejandro.sanchez@example.com",
    "ciudad": "Madrid",
    "pais": "Spain",
    "salario": 38000,
    "edad": 32,
    "altura": 175,
    "peso": 170
  },
  {
    "nombres": "Ella",
    "apellidos": "Larsen",
    "correo": "ella.larsen@example.com",
    "ciudad": "Copenhagen",
    "pais": "Denmark",
    "salario": 43000,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Leon",
    "apellidos": "Hoffmann",
    "correo": "leon.hoffmann@example.com",
    "ciudad": "Berlin",
    "pais": "Germany",
    "salario": 39000,
    "edad": 30,
    "altura": 180,
    "peso": 175
  },
  {
    "nombres": "Giorgia",
    "apellidos": "Rizzo",
    "correo": "giorgia.rizzo@example.com",
    "ciudad": "Rome",
    "pais": "Italy",
    "salario": 42000,
    "edad": 31,
    "altura": 160,
    "peso": 130
  },
  {
    "nombres": "Hugo",
    "apellidos": "Fernández",
    "correo": "hugo.fernandez@example.com",
    "ciudad": "Madrid",
    "pais": "Spain",
    "salario": 38000,
    "edad": 32,
    "altura": 175,
    "peso": 170
  },
  {
    "nombres": "Nora",
    "apellidos": "Christensen",
    "correo": "nora.christensen@example.com",
    "ciudad": "Copenhagen",
    "pais": "Denmark",
    "salario": 43000,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Felix",
    "apellidos": "Lehmann",
    "correo": "felix.lehmann@example.com",
    "ciudad": "Berlin",
    "pais": "Germany",
    "salario": 0,
    "edad": 30,
    "altura": 180,
    "peso": 175
  },
  {
    "nombres": "Alessia",
    "apellidos": "Martini",
    "correo": "alessia.martini@example.com",
    "ciudad": "Rome",
    "pais": "Italy",
    "salario": 42000,
    "edad": 31,
    "altura": 160,
    "peso": 130
  },
  {
    "nombres": "Javier",
    "apellidos": "Gómez",
    "correo": "javier.gomez@example.com",
    "ciudad": "Madrid",
    "pais": "Spain",
    "salario": 38000,
    "edad": 32,
    "altura": 175,
    "peso": 170
  },
  {
    "nombres": "Malou",
    "apellidos": "Petersen",
    "correo": "malou.petersen@example.com",
    "ciudad": "Copenhagen",
    "pais": "Denmark",
    "salario": 43000,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Friedrich",
    "apellidos": "Schmidt",
    "correo": "friedrich.schmidt@example.com",
    "ciudad": "Berlin",
    "pais": "Germany",
    "salario": 39000,
    "edad": 30,
    "altura": 180,
    "peso": 175
  },
  {
    "nombres": "Caterina",
    "apellidos": "De Angelis",
    "correo": "caterina.deangelis@example.com",
    "ciudad": "Rome",
    "pais": "Italy",
    "salario": 42000,
    "edad": 31,
    "altura": 160,
    "peso": 130
  },
  {
    "nombres": "Marcos",
    "apellidos": "Martínez",
    "correo": "marcos.martinez@example.com",
    "ciudad": "Madrid",
    "pais": "Spain",
    "salario": 0,
    "edad": 32,
    "altura": 175,
    "peso": 170
  },
  {
    "nombres": "Sophie",
    "apellidos": "Larsen",
    "correo": "sophie.larsen@example.com",
    "ciudad": "Copenhagen",
    "pais": "Denmark",
    "salario": 0,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Leon",
    "apellidos": "Hoffmann",
    "correo": "leon.hoffmann@example.com",
    "ciudad": "Berlin",
    "pais": "Germany",
    "salario": 39000,
    "edad": 30,
    "altura": 180,
    "peso": 175
  },
  {
    "nombres": "Giorgia",
    "apellidos": "Rizzo",
    "correo": "giorgia.rizzo@example.com",
    "ciudad": "Rome",
    "pais": "Italy",
    "salario": 42000,
    "edad": 31,
    "altura": 160,
    "peso": 130
  },
  {
    "nombres": "Hugo",
    "apellidos": "Fernández",
    "correo": "hugo.fernandez@example.com",
    "ciudad": "Madrid",
    "pais": "Spain",
    "salario": 38000,
    "edad": 32,
    "altura": 175,
    "peso": 170
  },
  {
    "nombres": "Nora",
    "apellidos": "Christensen",
    "correo": "nora.christensen@example.com",
    "ciudad": "Copenhagen",
    "pais": "Denmark",
    "salario": 43000,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Sophia",
    "apellidos": "Andersen",
    "correo": "sophia.andersen@example.com",
    "ciudad": "Copenhagen",
    "pais": "Denmark",
    "salario": 48000,
    "edad": 29,
    "altura": 167,
    "peso": 135
  },
  {
    "nombres": "Lukas",
    "apellidos": "Schmidt",
    "correo": "lukas.schmidt@example.com",
    "ciudad": "Berlin",
    "pais": "Germany",
    "salario": 43000,
    "edad": 33,
    "altura": 178,
    "peso": 170
  },
  {
    "nombres": "Alessia",
    "apellidos": "Ricci",
    "correo": "alessia.ricci@example.com",
    "ciudad": "Rome",
    "pais": "Italy",
    "salario": 39000,
    "edad": 30,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Pablo",
    "apellidos": "González",
    "correo": "pablo.gonzalez@example.com",
    "ciudad": "Madrid",
    "pais": "Spain",
    "salario": 42000,
    "edad": 31,
    "altura": 180,
    "peso": 170
  },
  {
    "nombres": "Emma",
    "apellidos": "Lindberg",
    "correo": "emma.lindberg@example.com",
    "ciudad": "Stockholm",
    "pais": "Sweden",
    "salario": 40000,
    "edad": 27,
    "altura": 175,
    "peso": 180
  },
  {
    "nombres": "Niklas",
    "apellidos": "Andersson",
    "correo": "niklas.andersson@example.com",
    "ciudad": "Oslo",
    "pais": "Norway",
    "salario": 45000,
    "edad": 30,
    "altura": 165,
    "peso": 145
  },
  {
    "nombres": "Laura",
    "apellidos": "Martínez",
    "correo": "laura.martinez@example.com",
    "ciudad": "Barcelona",
    "pais": "Spain",
    "salario": 37000,
    "edad": 29,
    "altura": 162,
    "peso": 135
  },
  {
    "nombres": "Liam",
    "apellidos": "Smith",
    "correo": "liam.smith@example.com",
    "ciudad": "London",
    "pais": "UK",
    "salario": 46000,
    "edad": 31,
    "altura": 167,
    "peso": 140
  },
  {
    "nombres": "Hanna",
    "apellidos": "Nielsen",
    "correo": "hanna.nielsen@example.com",
    "ciudad": "Copenhagen",
    "pais": "Denmark",
    "salario": 43000,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Maximilian",
    "apellidos": "Müller",
    "correo": "maximilian.muller@example.com",
    "ciudad": "Berlin",
    "pais": "Germany",
    "salario": 39000,
    "edad": 30,
    "altura": 180,
    "peso": 175
  },
  {
    "nombres": "Giulia",
    "apellidos": "Rossi",
    "correo": "giulia.rossi@example.com",
    "ciudad": "Rome",
    "pais": "Italy",
    "salario": 42000,
    "edad": 31,
    "altura": 160,
    "peso": 130
  },
  {
    "nombres": "Santiago",
    "apellidos": "López",
    "correo": "santiago.lopez@example.com",
    "ciudad": "Madrid",
    "pais": "Spain",
    "salario": 38000,
    "edad": 32,
    "altura": 175,
    "peso": 170
  },
  {
    "nombres": "Elsa",
    "apellidos": "Andersson",
    "correo": "elsa.andersson@example.com",
    "ciudad": "Stockholm",
    "pais": "Sweden",
    "salario": 40000,
    "edad": 27,
    "altura": 175,
    "peso": 180
  },
  {
    "nombres": "Oskar",
    "apellidos": "Berg",
    "correo": "oskar.berg@example.com",
    "ciudad": "Oslo",
    "pais": "Norway",
    "salario": 45000,
    "edad": 30,
    "altura": 165,
    "peso": 145
  },
  {
    "nombres": "Elena",
    "apellidos": "García",
    "correo": "elena.garcia@example.com",
    "ciudad": "Barcelona",
    "pais": "Spain",
    "salario": 37000,
    "edad": 29,
    "altura": 162,
    "peso": 135
  },
  {
    "nombres": "James",
    "apellidos": "Johnson",
    "correo": "james.johnson@example.com",
    "ciudad": "London",
    "pais": "UK",
    "salario": 46000,
    "edad": 31,
    "altura": 167,
    "peso": 140
  },
  {
    "nombres": "Freja",
    "apellidos": "Nielsen",
    "correo": "freja.nielsen@example.com",
    "ciudad": "Copenhagen",
    "pais": "Denmark",
    "salario": 43000,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Lukas",
    "apellidos": "Schneider",
    "correo": "lukas.schneider@example.com",
    "ciudad": "Berlin",
    "pais": "Germany",
    "salario": 39000,
    "edad": 30,
    "altura": 180,
    "peso": 175
  },
  {
    "nombres": "Jean",
    "apellidos": "Dupont",
    "correo": "jean.dupont@example.com",
    "ciudad": "Paris",
    "pais": "France",
    "salario": 50000,
    "edad": 35,
    "altura": 175,
    "peso": 160
  },
  {
    "nombres": "Marie",
    "apellidos": "Lefevre",
    "correo": "marie.lefevre@example.com",
    "ciudad": "Lyon",
    "pais": "France",
    "salario": 48000,
    "edad": 28,
    "altura": 163,
    "peso": 130
  },
  {
    "nombres": "Pierre",
    "apellidos": "Leroy",
    "correo": "pierre.leroy@example.com",
    "ciudad": "Marseille",
    "pais": "France",
    "salario": 52000,
    "edad": 40,
    "altura": 180,
    "peso": 175
  },
  {
    "nombres": "Sophie",
    "apellidos": "Moreau",
    "correo": "sophie.moreau@example.com",
    "ciudad": "Toulouse",
    "pais": "France",
    "salario": 45000,
    "edad": 31,
    "altura": 168,
    "peso": 140
  },
  {
    "nombres": "Nicolas",
    "apellidos": "Roux",
    "correo": "nicolas.roux@example.com",
    "ciudad": "Nice",
    "pais": "France",
    "salario": 47000,
    "edad": 29,
    "altura": 175,
    "peso": 165
  },
  {
    "nombres": "Camille",
    "apellidos": "Garcia",
    "correo": "camille.garcia@example.com",
    "ciudad": "Lille",
    "pais": "France",
    "salario": 49000,
    "edad": 33,
    "altura": 170,
    "peso": 150
  },
  {
    "nombres": "Thomas",
    "apellidos": "Fournier",
    "correo": "thomas.fournier@example.com",
    "ciudad": "Bordeaux",
    "pais": "France",
    "salario": 51000,
    "edad": 36,
    "altura": 182,
    "peso": 180
  },
  {
    "nombres": "Manon",
    "apellidos": "Martinez",
    "correo": "manon.martinez@example.com",
    "ciudad": "Montpellier",
    "pais": "France",
    "salario": 46000,
    "edad": 30,
    "altura": 165,
    "peso": 140
  },
  {
    "nombres": "Antoine",
    "apellidos": "Legrand",
    "correo": "antoine.legrand@example.com",
    "ciudad": "Strasbourg",
    "pais": "France",
    "salario": 48000,
    "edad": 32,
    "altura": 178,
    "peso": 170
  },
  {
    "nombres": "Julie",
    "apellidos": "Rousseau",
    "correo": "julie.rousseau@example.com",
    "ciudad": "Nantes",
    "pais": "France",
    "salario": 47000,
    "edad": 29,
    "altura": 163,
    "peso": 130
  },
  {
    "nombres": "Lucas",
    "apellidos": "Garnier",
    "correo": "lucas.garnier@example.com",
    "ciudad": "Rennes",
    "pais": "France",
    "salario": 49000,
    "edad": 33,
    "altura": 175,
    "peso": 160
  },
  {
    "nombres": "Charlotte",
    "apellidos": "Lemoine",
    "correo": "charlotte.lemoine@example.com",
    "ciudad": "Reims",
    "pais": "France",
    "salario": 46000,
    "edad": 30,
    "altura": 170,
    "peso": 145
  },
  {
    "nombres": "Mathieu",
    "apellidos": "Barreau",
    "correo": "mathieu.barreau@example.com",
    "ciudad": "Le Havre",
    "pais": "France",
    "salario": 50000,
    "edad": 35,
    "altura": 180,
    "peso": 175
  },
  {
    "nombres": "Sarah",
    "apellidos": "Vincent",
    "correo": "sarah.vincent@example.com",
    "ciudad": "Toulon",
    "pais": "France",
    "salario": 45000,
    "edad": 31,
    "altura": 168,
    "peso": 140
  },
  {
    "nombres": "Romain",
    "apellidos": "Benoit",
    "correo": "romain.benoit@example.com",
    "ciudad": "Grenoble",
    "pais": "France",
    "salario": 49000,
    "edad": 33,
    "altura": 175,
    "peso": 160
  },
  {
    "nombres": "Elodie",
    "apellidos": "Rey",
    "correo": "elodie.rey@example.com",
    "ciudad": "Dijon",
    "pais": "France",
    "salario": 48000,
    "edad": 32,
    "altura": 170,
    "peso": 150
  },
  {
    "nombres": "Vincent",
    "apellidos": "Lefevre",
    "correo": "vincent.lefevre@example.com",
    "ciudad": "Angers",
    "pais": "France",
    "salario": 47000,
    "edad": 29,
    "altura": 175,
    "peso": 165
  },
  {
    "nombres": "Céline",
    "apellidos": "Brun",
    "correo": "celine.brun@example.com",
    "ciudad": "Metz",
    "pais": "France",
    "salario": 48000,
    "edad": 32,
    "altura": 178,
    "peso": 170
  },
  {
    "nombres": "Camille",
    "apellidos": "Lefevre",
    "correo": "camille.lefevre@example.com",
    "ciudad": "Paris",
    "pais": "France",
    "salario": 38000,
    "edad": 19,
    "altura": 163,
    "peso": 130
  },
  {
    "nombres": "Lucas",
    "apellidos": "Dubois",
    "correo": "lucas.dubois@example.com",
    "ciudad": "Marseille",
    "pais": "France",
    "salario": 36000,
    "edad": 18,
    "altura": 175,
    "peso": 155
  },
  {
    "nombres": "Emma",
    "apellidos": "Moreau",
    "correo": "emma.moreau@example.com",
    "ciudad": "Paris",
    "pais": "France",
    "salario": 37000,
    "edad": 20,
    "altura": 168,
    "peso": 140
  },
  {
    "nombres": "Louis",
    "apellidos": "Garcia",
    "correo": "louis.garcia@example.com",
    "ciudad": "Toulouse",
    "pais": "France",
    "salario": 39000,
    "edad": 17,
    "altura": 170,
    "peso": 150
  },
  {
    "nombres": "Chloé",
    "apellidos": "Martinez",
    "correo": "chloe.martinez@example.com",
    "ciudad": "Paris",
    "pais": "France",
    "salario": 40000,
    "edad": 18,
    "altura": 165,
    "peso": 135
  },
  {
    "nombres": "Mathis",
    "apellidos": "Legrand",
    "correo": "mathis.legrand@example.com",
    "ciudad": "Lyon",
    "pais": "France",
    "salario": 38000,
    "edad": 19,
    "altura": 178,
    "peso": 160
  },
  {
    "nombres": "Manon",
    "apellidos": "Roux",
    "correo": "manon.roux@example.com",
    "ciudad": "Paris",
    "pais": "France",
    "salario": 37000,
    "edad": 20,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Hugo",
    "apellidos": "Fournier",
    "correo": "hugo.fournier@example.com",
    "ciudad": "Nice",
    "pais": "France",
    "salario": 36000,
    "edad": 18,
    "altura": 180,
    "peso": 170
  },
  {
    "nombres": "Jade",
    "apellidos": "Morel",
    "correo": "jade.morel@example.com",
    "ciudad": "Paris",
    "pais": "France",
    "salario": 39000,
    "edad": 19,
    "altura": 168,
    "peso": 140
  },
  {
    "nombres": "Noah",
    "apellidos": "Garnier",
    "correo": "noah.garnier@example.com",
    "ciudad": "Marseille",
    "pais": "France",
    "salario": 37000,
    "edad": 17,
    "altura": 175,
    "peso": 165
  },
  {
    "nombres": "Léa",
    "apellidos": "Brun",
    "correo": "lea.brun@example.com",
    "ciudad": "Paris",
    "pais": "France",
    "salario": 38000,
    "edad": 18,
    "altura": 163,
    "peso": 150
  },
  {
    "nombres": "Ethan",
    "apellidos": "Mercier",
    "correo": "ethan.mercier@example.com",
    "ciudad": "Toulouse",
    "pais": "France",
    "salario": 40000,
    "edad": 20,
    "altura": 170,
    "peso": 160
  },
  {
    "nombres": "Léa",
    "apellidos": "Barreau",
    "correo": "lea.barreau@example.com",
    "ciudad": "Paris",
    "pais": "France",
    "salario": 39000,
    "edad": 19,
    "altura": 178,
    "peso": 170
  },
  {
    "nombres": "Théo",
    "apellidos": "Rey",
    "correo": "theo.rey@example.com",
    "ciudad": "Lyon",
    "pais": "France",
    "salario": 38000,
    "edad": 18,
    "altura": 165,
    "peso": 145
  },
  {
    "nombres": "Inès",
    "apellidos": "Lemoine",
    "correo": "ines.lemoine@example.com",
    "ciudad": "Paris",
    "pais": "France",
    "salario": 40000,
    "edad": 20,
    "altura": 170,
    "peso": 145
  },
  {
    "nombres": "Lucas",
    "apellidos": "Brun",
    "correo": "lucas.brun@example.com",
    "ciudad": "Marseille",
    "pais": "France",
    "salario": 37000,
    "edad": 17,
    "altura": 175,
    "peso": 160
  },
  {
    "nombres": "Léa",
    "apellidos": "Roy",
    "correo": "lea.roy@example.com",
    "ciudad": "Paris",
    "pais": "France",
    "salario": 39000,
    "edad": 18,
    "altura": 163,
    "peso": 130
  },
  {
    "nombres": "Maxime",
    "apellidos": "Lefevre",
    "correo": "maxime.lefevre@example.com",
    "ciudad": "Lyon",
    "pais": "France",
    "salario": 38000,
    "edad": 19,
    "altura": 178,
    "peso": 160
  },
  {
    "nombres": "Manon",
    "apellidos": "Roux",
    "correo": "manon.roux@example.com",
    "ciudad": "Paris",
    "pais": "France",
    "salario": 37000,
    "edad": 20,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Hugo",
    "apellidos": "Fournier",
    "correo": "hugo.fournier@example.com",
    "ciudad": "Nice",
    "pais": "France",
    "salario": 36000,
    "edad": 18,
    "altura": 180,
    "peso": 170
  },
  {
    "nombres": "Juan",
    "apellidos": "Garcia",
    "correo": "juan.garcia@example.com",
    "ciudad": "Buenos Aires",
    "pais": "Argentina",
    "salario": 1500,
    "edad": 18,
    "altura": 170,
    "peso": 140
  },
  {
    "nombres": "Maria",
    "apellidos": "Silva",
    "correo": "maria.silva@example.com",
    "ciudad": "Sao Paulo",
    "pais": "Brazil",
    "salario": 1800,
    "edad": 19,
    "altura": 165,
    "peso": 130
  },
  {
    "nombres": "Luis",
    "apellidos": "Lopez",
    "correo": "luis.lopez@example.com",
    "ciudad": "Mexico City",
    "pais": "Mexico",
    "salario": 1700,
    "edad": 20,
    "altura": 180,
    "peso": 150
  },
  {
    "nombres": "Ana",
    "apellidos": "Hernandez",
    "correo": "ana.hernandez@example.com",
    "ciudad": "Lima",
    "pais": "Peru",
    "salario": 1900,
    "edad": 17,
    "altura": 165,
    "peso": 135
  },
  {
    "nombres": "Carlos",
    "apellidos": "Perez",
    "correo": "carlos.perez@example.com",
    "ciudad": "Santiago",
    "pais": "Chile",
    "salario": 1750,
    "edad": 18,
    "altura": 168,
    "peso": 120
  },
  {
    "nombres": "Sofia",
    "apellidos": "Gomez",
    "correo": "sofia.gomez@example.com",
    "ciudad": "Bogota",
    "pais": "Colombia",
    "salario": 1950,
    "edad": 19,
    "altura": 172,
    "peso": 155
  },
  {
    "nombres": "Diego",
    "apellidos": "Torres",
    "correo": "diego.torres@example.com",
    "ciudad": "Lima",
    "pais": "Peru",
    "salario": 1750,
    "edad": 20,
    "altura": 168,
    "peso": 140
  },
  {
    "nombres": "Valentina",
    "apellidos": "Rodriguez",
    "correo": "valentina.rodriguez@example.com",
    "ciudad": "Buenos Aires",
    "pais": "Argentina",
    "salario": 1850,
    "edad": 17,
    "altura": 172,
    "peso": 125
  },
  {
    "nombres": "Mateo",
    "apellidos": "Martinez",
    "correo": "mateo.martinez@example.com",
    "ciudad": "Bogota",
    "pais": "Colombia",
    "salario": 1550,
    "edad": 18,
    "altura": 180,
    "peso": 160
  },
  {
    "nombres": "Isabella",
    "apellidos": "Gutierrez",
    "correo": "isabella.gutierrez@example.com",
    "ciudad": "Mexico City",
    "pais": "Mexico",
    "salario": 1650,
    "edad": 19,
    "altura": 168,
    "peso": 145
  },
  {
    "nombres": "Gabriel",
    "apellidos": "Rojas",
    "correo": "gabriel.rojas@example.com",
    "ciudad": "Santiago",
    "pais": "Chile",
    "salario": 1950,
    "edad": 20,
    "altura": 175,
    "peso": 160
  },
  {
    "nombres": "Valeria",
    "apellidos": "Perez",
    "correo": "valeria.perez@example.com",
    "ciudad": "Lima",
    "pais": "Peru",
    "salario": 1750,
    "edad": 19,
    "altura": 178,
    "peso": 170
  },
  {
    "nombres": "Lucas",
    "apellidos": "Herrera",
    "correo": "lucas.herrera@example.com",
    "ciudad": "Buenos Aires",
    "pais": "Argentina",
    "salario": 1600,
    "edad": 20,
    "altura": 165,
    "peso": 150
  },
  {
    "nombres": "Camila",
    "apellidos": "Santos",
    "correo": "camila.santos@example.com",
    "ciudad": "Sao Paulo",
    "pais": "Brazil",
    "salario": 1700,
    "edad": 19,
    "altura": 178,
    "peso": 170
  },
  {
    "nombres": "Liam",
    "apellidos": "Smith",
    "correo": "liam.smith@example.com",
    "ciudad": "Toronto",
    "pais": "Canada",
    "salario": 4000,
    "edad": 18,
    "altura": 175,
    "peso": 160
  },
  {
    "nombres": "Emma",
    "apellidos": "Johnson",
    "correo": "emma.johnson@example.com",
    "ciudad": "Vancouver",
    "pais": "Canada",
    "salario": 4500,
    "edad": 19,
    "altura": 170,
    "peso": 140
  },
  {
    "nombres": "William",
    "apellidos": "Williams",
    "correo": "william.williams@example.com",
    "ciudad": "Montreal",
    "pais": "Canada",
    "salario": 3500,
    "edad": 20,
    "altura": 180,
    "peso": 150
  },
  {
    "nombres": "Olivia",
    "apellidos": "Brown",
    "correo": "olivia.brown@example.com",
    "ciudad": "Calgary",
    "pais": "Canada",
    "salario": 3800,
    "edad": 17,
    "altura": 165,
    "peso": 135
  },
  {
    "nombres": "James",
    "apellidos": "Jones",
    "correo": "james.jones@example.com",
    "ciudad": "Ottawa",
    "pais": "Canada",
    "salario": 4200,
    "edad": 18,
    "altura": 168,
    "peso": 120
  },
  {
    "nombres": "Ava",
    "apellidos": "Miller",
    "correo": "ava.miller@example.com",
    "ciudad": "Edmonton",
    "pais": "Canada",
    "salario": 4700,
    "edad": 19,
    "altura": 172,
    "peso": 155
  },
  {
    "nombres": "Alexander",
    "apellidos": "Davis",
    "correo": "alexander.davis@example.com",
    "ciudad": "Quebec City",
    "pais": "Canada",
    "salario": 3900,
    "edad": 20,
    "altura": 168,
    "peso": 140
  },
  {
    "nombres": "Mia",
    "apellidos": "Garcia",
    "correo": "mia.garcia@example.com",
    "ciudad": "Winnipeg",
    "pais": "Canada",
    "salario": 4800,
    "edad": 17,
    "altura": 172,
    "peso": 125
  },
  {
    "nombres": "Ethan",
    "apellidos": "Rodriguez",
    "correo": "ethan.rodriguez@example.com",
    "ciudad": "Halifax",
    "pais": "Canada",
    "salario": 3200,
    "edad": 18,
    "altura": 180,
    "peso": 160
  },
  {
    "nombres": "Sophia",
    "apellidos": "Martinez",
    "correo": "sophia.martinez@example.com",
    "ciudad": "Regina",
    "pais": "Canada",
    "salario": 3600,
    "edad": 19,
    "altura": 168,
    "peso": 145
  },
  {
    "nombres": "Michael",
    "apellidos": "Hernandez",
    "correo": "michael.hernandez@example.com",
    "ciudad": "St. John's",
    "pais": "Canada",
    "salario": 4900,
    "edad": 20,
    "altura": 175,
    "peso": 160
  },
  {
    "nombres": "Isabella",
    "apellidos": "Lopez",
    "correo": "isabella.lopez@example.com",
    "ciudad": "Victoria",
    "pais": "Canada",
    "salario": 3700,
    "edad": 19,
    "altura": 178,
    "peso": 170
  },
  {
    "nombres": "William",
    "apellidos": "Wright",
    "correo": "william.wright@example.com",
    "ciudad": "Saskatoon",
    "pais": "Canada",
    "salario": 3300,
    "edad": 20,
    "altura": 165,
    "peso": 150
  },
  {
    "nombres": "Emma",
    "apellidos": "Gonzalez",
    "correo": "emma.gonzalez@example.com",
    "ciudad": "Charlottetown",
    "pais": "Canada",
    "salario": 4000,
    "edad": 19,
    "altura": 178,
    "peso": 170
  },
  {
    "nombres": "Liam",
    "apellidos": "Perez",
    "correo": "liam.perez@example.com",
    "ciudad": "Whitehorse",
    "pais": "Canada",
    "salario": 4100,
    "edad": 18,
    "altura": 178,
    "peso": 160
  },
  {
    "nombres": "Olivia",
    "apellidos": "Torres",
    "correo": "olivia.torres@example.com",
    "ciudad": "Yellowknife",
    "pais": "Canada",
    "salario": 4600,
    "edad": 17,
    "altura": 175,
    "peso": 160
  },
  {
    "nombres": "Noah",
    "apellidos": "Ramirez",
    "correo": "noah.ramirez@example.com",
    "ciudad": "Iqaluit",
    "pais": "Canada",
    "salario": 4400,
    "edad": 18,
    "altura": 163,
    "peso": 130
  },
  {
    "nombres": "Lucas",
    "apellidos": "Silva",
    "correo": "lucas.silva@example.com",
    "ciudad": "Sao Paulo",
    "pais": "Brazil",
    "salario": 3200,
    "edad": 18,
    "altura": 175,
    "peso": 150
  },
  {
    "nombres": "Isabella",
    "apellidos": "Santos",
    "correo": "isabella.santos@example.com",
    "ciudad": "Rio de Janeiro",
    "pais": "Brazil",
    "salario": 3500,
    "edad": 19,
    "altura": 168,
    "peso": 130
  },
  {
    "nombres": "Enzo",
    "apellidos": "Oliveira",
    "correo": "enzo.oliveira@example.com",
    "ciudad": "Salvador",
    "pais": "Brazil",
    "salario": 3700,
    "edad": 20,
    "altura": 180,
    "peso": 140
  },
  {
    "nombres": "Manuela",
    "apellidos": "Souza",
    "correo": "manuela.souza@example.com",
    "ciudad": "Brasilia",
    "pais": "Brazil",
    "salario": 3400,
    "edad": 17,
    "altura": 165,
    "peso": 120
  },
  {
    "nombres": "Miguel",
    "apellidos": "Ribeiro",
    "correo": "miguel.ribeiro@example.com",
    "ciudad": "Fortaleza",
    "pais": "Brazil",
    "salario": 3800,
    "edad": 18,
    "altura": 170,
    "peso": 155
  },
  {
    "nombres": "Lara",
    "apellidos": "Costa",
    "correo": "lara.costa@example.com",
    "ciudad": "Manaus",
    "pais": "Brazil",
    "salario": 4000,
    "edad": 19,
    "altura": 172,
    "peso": 145
  },
  {
    "nombres": "Raul",
    "apellidos": "Mendes",
    "correo": "raul.mendes@example.com",
    "ciudad": "Recife",
    "pais": "Brazil",
    "salario": 3600,
    "edad": 20,
    "altura": 168,
    "peso": 140
  },
  {
    "nombres": "Helena",
    "apellidos": "Barbosa",
    "correo": "helena.barbosa@example.com",
    "ciudad": "Porto Alegre",
    "pais": "Brazil",
    "salario": 4200,
    "edad": 17,
    "altura": 172,
    "peso": 125
  },
  {
    "nombres": "Arthur",
    "apellidos": "Fernandes",
    "correo": "arthur.fernandes@example.com",
    "ciudad": "Curitiba",
    "pais": "Brazil",
    "salario": 4500,
    "edad": 18,
    "altura": 180,
    "peso": 160
  },
  {
    "nombres": "Laura",
    "apellidos": "Carvalho",
    "correo": "laura.carvalho@example.com",
    "ciudad": "Belém",
    "pais": "Brazil",
    "salario": 3700,
    "edad": 19,
    "altura": 168,
    "peso": 145
  },
  {
    "nombres": "Pedro",
    "apellidos": "Pereira",
    "correo": "pedro.pereira@example.com",
    "ciudad": "Goiania",
    "pais": "Brazil",
    "salario": 4800,
    "edad": 20,
    "altura": 175,
    "peso": 160
  },
  {
    "nombres": "Luna",
    "apellidos": "Gomes",
    "correo": "luna.gomes@example.com",
    "ciudad": "Sao Luis",
    "pais": "Brazil",
    "salario": 3900,
    "edad": 19,
    "altura": 178,
    "peso": 170
  },
  {
    "nombres": "Henrique",
    "apellidos": "Araujo",
    "correo": "henrique.araujo@example.com",
    "ciudad": "Joao Pessoa",
    "pais": "Brazil",
    "salario": 3300,
    "edad": 20,
    "altura": 165,
    "peso": 150
  },
  {
    "nombres": "Ana",
    "apellidos": "Lima",
    "correo": "ana.lima@example.com",
    "ciudad": "Teresina",
    "pais": "Brazil",
    "salario": 4000,
    "edad": 19,
    "altura": 178,
    "peso": 155
  },
  {
    "nombres": "Aarav",
    "apellidos": "Sharma",
    "correo": "aarav.sharma@example.com",
    "ciudad": "Mumbai",
    "pais": "India",
    "salario": 2500,
    "edad": 18,
    "altura": 170,
    "peso": 140
  },
  {
    "nombres": "Saachi",
    "apellidos": "Patel",
    "ciudad": "Delhi",
    "pais": "India",
    "salario": 2800,
    "edad": 19,
    "altura": 165,
    "peso": 130
  },
  {
    "nombres": "Vihaan",
    "apellidos": "Kumar",
    "correo": "vihaan.kumar@example.com",
    "ciudad": "Kolkata",
    "pais": "India",
    "salario": 2900,
    "edad": 20,
    "altura": 175,
    "peso": 150
  },
  {
    "nombres": "Aadhya",
    "apellidos": "Singh",
    "correo": "aadhya.singh@example.com",
    "ciudad": "Chennai",
    "pais": "India",
    "salario": 2700,
    "edad": 17,
    "altura": 160,
    "peso": 120
  },
  {
    "nombres": "Reyansh",
    "apellidos": "Gupta",
    "ciudad": "Bangalore",
    "pais": "India",
    "salario": 3000,
    "edad": 18,
    "altura": 170,
    "peso": 155
  },
  {
    "nombres": "Diya",
    "apellidos": "Verma",
    "correo": "diya.verma@example.com",
    "ciudad": "Hyderabad",
    "pais": "India",
    "salario": 2600,
    "edad": 19,
    "altura": 168,
    "peso": 145
  },
  {
    "nombres": "Advik",
    "apellidos": "Choudhury",
    "correo": "advik.choudhury@example.com",
    "ciudad": "Pune",
    "pais": "India",
    "salario": 3200,
    "edad": 20,
    "altura": 175,
    "peso": 160
  },
  {
    "nombres": "Ishaan",
    "apellidos": "Sinha",
    "ciudad": "Jaipur",
    "pais": "India",
    "salario": 2900,
    "edad": 17,
    "altura": 165,
    "peso": 125
  },
  {
    "nombres": "Anaya",
    "apellidos": "Dutta",
    "correo": "anaya.dutta@example.com",
    "ciudad": "Ahmedabad",
    "pais": "India",
    "salario": 3100,
    "edad": 18,
    "altura": 170,
    "peso": 160
  },
  {
    "nombres": "Vihaan",
    "apellidos": "Shah",
    "ciudad": "Surat",
    "pais": "India",
    "salario": 2800,
    "edad": 19,
    "altura": 168,
    "peso": 145
  },
  {
    "nombres": "Amaira",
    "apellidos": "Das",
    "correo": "amaira.das@example.com",
    "ciudad": "Lucknow",
    "pais": "India",
    "salario": 3300,
    "edad": 20,
    "altura": 173,
    "peso": 150
  },
  {
    "nombres": "Shaurya",
    "apellidos": "Rao",
    "correo": "shaurya.rao@example.com",
    "ciudad": "Nagpur",
    "pais": "India",
    "salario": 2700,
    "edad": 19,
    "altura": 172,
    "peso": 170
  },
  {
    "nombres": "Ananya",
    "apellidos": "Goswami",
    "correo": "ananya.goswami@example.com",
    "ciudad": "Indore",
    "pais": "India",
    "salario": 3000,
    "edad": 18,
    "altura": 168,
    "peso": 150
  },
  {
    "nombres": "Yuvraj",
    "apellidos": "Mehta",
    "ciudad": "Vadodara",
    "pais": "India",
    "salario": 2900,
    "edad": 20,
    "altura": 176,
    "peso": 155
  },
  {
    "nombres": "Zara",
    "apellidos": "Banerjee",
    "correo": "zara.banerjee@example.com",
    "ciudad": "Agra",
    "pais": "India",
    "salario": 3100,
    "edad": 19,
    "altura": 170,
    "peso": 140
  },
  {
    "nombres": "Arjun",
    "apellidos": "Saxena",
    "correo": "arjun.saxena@example.com",
    "ciudad": "Varanasi",
    "pais": "India",
    "salario": 2800,
    "edad": 18,
    "altura": 174,
    "peso": 160
  },
  {
    "nombres": "Juan",
    "apellidos": "Gonzalez",
    "correo": "nuevo@riwi.io",
    "ciudad": "Mumbai",
    "pais": "India",
    "salario": 2500,
    "edad": 19,
    "altura": 175,
    "peso": 155
  },
  {
    "nombres": "Maria",
    "apellidos": "Rodriguez",
    "correo": "ejemplo@riwi.io",
    "ciudad": "Delhi",
    "pais": "India",
    "salario": 2600,
    "edad": 18,
    "altura": 170,
    "peso": 150
  },
  {
    "nombres": "Ravi",
    "apellidos": "Kumar",
    "correo": "otro@riwi.io",
    "ciudad": "Bangalore",
    "pais": "India",
    "salario": 2800,
    "edad": 17,
    "altura": 165,
    "peso": 140
  },
  {
    "nombres": "Sunita",
    "apellidos": "Patel",
    "correo": "nuevo_correo@riwi.io",
    "ciudad": "Kolkata",
    "pais": "India",
    "salario": 2700,
    "edad": 19,
    "altura": 168,
    "peso": 145
  },
  {
    "nombres": "Raj",
    "apellidos": "Singh",
    "correo": "nuevo@riwi.io",
    "ciudad": "Chennai",
    "pais": "India",
    "salario": 2900,
    "edad": 18,
    "altura": 172,
    "peso": 150
  },
  {
    "nombres": "Priya",
    "apellidos": "Sharma",
    "correo": "ejemplo@riwi.io",
    "ciudad": "Hyderabad",
    "pais": "India",
    "salario": 2550,
    "edad": 19,
    "altura": 170,
    "peso": 155
  },
  {
    "nombres": "Amit",
    "apellidos": "Gupta",
    "correo": "otro@riwi.io",
    "ciudad": "Pune",
    "pais": "India",
    "salario": 2650,
    "edad": 17,
    "altura": 175,
    "peso": 160
  },
  {
    "nombres": "Anjali",
    "apellidos": "Yadav",
    "correo": "nuevo_correo@riwi.io",
    "ciudad": "Ahmedabad",
    "pais": "India",
    "salario": 2750,
    "edad": 18,
    "altura": 168,
    "peso": 145
  },
  {
    "nombres": "Sanjay",
    "apellidos": "Shah",
    "correo": "nuevo@riwi.io",
    "ciudad": "Jaipur",
    "pais": "India",
    "salario": 2850,
    "edad": 19,
    "altura": 172,
    "peso": 150
  },
  {
    "nombres": "Neeta",
    "apellidos": "Verma",
    "correo": "ejemplo@riwi.io",
    "ciudad": "Lucknow",
    "pais": "India",
    "salario": 2950,
    "edad": 17,
    "altura": 170,
    "peso": 155
  },
  {
    "nombres": "Rahul",
    "apellidos": "Jain",
    "correo": "otro@riwi.io",
    "ciudad": "Surat",
    "pais": "India",
    "salario": 2600,
    "edad": 18,
    "altura": 175,
    "peso": 160
  },
  {
    "nombres": "Poonam",
    "apellidos": "Mishra",
    "correo": "nuevo_correo@riwi.io",
    "ciudad": "Nagpur",
    "pais": "India",
    "salario": 2700,
    "edad": 19,
    "altura": 168,
    "peso": 145
  },
  {
    "nombres": "Vikram",
    "apellidos": "Gandhi",
    "correo": "nuevo@riwi.io",
    "ciudad": "Indore",
    "pais": "India",
    "salario": 2800,
    "edad": 17,
    "altura": 172,
    "peso": 150
  },
  {
    "nombres": "Kavita",
    "apellidos": "Tiwari",
    "correo": "ejemplo@riwi.io",
    "ciudad": "Vadodara",
    "pais": "India",
    "salario": 2900,
    "edad": 18,
    "altura": 170,
    "peso": 155
  },
  {
    "nombres": "Deepak",
    "apellidos": "Chauhan",
    "correo": "otro@riwi.io",
    "ciudad": "Bhopal",
    "pais": "India",
    "salario": 2550,
    "edad": 19,
    "altura": 175,
    "peso": 160
  },
  {
    "nombres": "Sofia",
    "apellidos": "Singh",
    "correo": "nuevo@riwi.io",
    "ciudad": "Mumbai",
    "pais": "India",
    "salario": 2500,
    "edad": 19,
    "altura": 165,
    "peso": 110
  },
  {
    "nombres": "Arjun",
    "apellidos": "Patel",
    "correo": "ejemplo@riwi.io",
    "ciudad": "Delhi",
    "pais": "India",
    "salario": 2700,
    "edad": 18,
    "altura": 170,
    "peso": 120
  },
  {
    "nombres": "Aisha",
    "apellidos": "Kumar",
    "correo": "otro@riwi.io",
    "ciudad": "Bangalore",
    "pais": "India",
    "salario": 2900,
    "edad": 17,
    "altura": 163,
    "peso": 105
  },
  {
    "nombres": "Rohan",
    "apellidos": "Gupta",
    "correo": "nuevo_correo@riwi.io",
    "ciudad": "Kolkata",
    "pais": "India",
    "salario": 2800,
    "edad": 16,
    "altura": 175,
    "peso": 130
  },
  {
    "nombres": "Ishaan",
    "apellidos": "Sharma",
    "correo": "nuevo@riwi.io",
    "ciudad": "Chennai",
    "pais": "India",
    "salario": 2600,
    "edad": 15,
    "altura": 160,
    "peso": 100
  },
  {
    "nombres": "Aditi",
    "apellidos": "Das",
    "correo": "ejemplo@riwi.io",
    "ciudad": "Hyderabad",
    "pais": "India",
    "salario": 3000,
    "edad": 14,
    "altura": 155,
    "peso": 95
  },
  {
    "nombres": "Nihal",
    "apellidos": "Khan",
    "correo": "otro@riwi.io",
    "ciudad": "Pune",
    "pais": "India",
    "salario": 2800,
    "edad": 13,
    "altura": 145,
    "peso": 85
  },
  {
    "nombres": "Aarav",
    "apellidos": "Choudhury",
    "correo": "nuevo_correo@riwi.io",
    "ciudad": "Bello",
    "pais": "India",
    "salario": 2900,
    "edad": 12,
    "altura": 140,
    "peso": 80
  },
  {
    "nombres": "Anika",
    "apellidos": "Rao",
    "correo": "nuevo@riwi.io",
    "ciudad": "Jaipur",
    "pais": "India",
    "salario": 2700,
    "edad": 11,
    "altura": 135,
    "peso": 75
  },
  {
    "nombres": "Yuvraj",
    "apellidos": "Singhania",
    "correo": "ejemplo@riwi.io",
    "ciudad": "Lucknow",
    "pais": "India",
    "salario": 3100,
    "edad": 10,
    "altura": 130,
    "peso": 70
  },
  {
    "nombres": "Saanvi",
    "apellidos": "Malhotra",
    "correo": "otro@riwi.io",
    "ciudad": "Surat",
    "pais": "India",
    "salario": 2800,
    "edad": 9,
    "altura": 125,
    "peso": 65
  },
  {
    "nombres": "Vihaan",
    "apellidos": "Deshmukh",
    "correo": "nuevo_correo@riwi.io",
    "ciudad": "Nagpur",
    "pais": "India",
    "salario": 3000,
    "edad": 8,
    "altura": 120,
    "peso": 60
  },
  {
    "nombres": "Diya",
    "apellidos": "Iyer",
    "correo": "nuevo@riwi.io",
    "ciudad": "Indore",
    "pais": "India",
    "salario": 2600,
    "edad": 7,
    "altura": 115,
    "peso": 55
  },
  {
    "nombres": "Ravi",
    "apellidos": "Kumar",
    "correo": "ejemplo@riwi.io",
    "ciudad": "Mumbai",
    "pais": "India",
    "salario": 4000,
    "edad": 65,
    "altura": 170,
    "peso": 160
  },
  {
  "nombres": "Meera",
  "apellidos": "Sharma",
  "correo": "borrar@riwi.io",
  "ciudad": "Bello",
  "pais": "India",
  "salario": 4200,
  "edad": 70,
  "altura": 155,
  "peso": 150
  },
  {
  "nombres": "Amit",
  "apellidos": "Patel",
  "correo": "ejemplo@riwi.io",
  "ciudad": "Bangalore",
  "pais": "India",
  "salario": 3800,
  "edad": 65,
  "altura": 165,
  "peso": 155
  },
  {
  "nombres": "Lata",
  "apellidos": "Gupta",
  "correo": "borrar@riwi.io",
  "ciudad": "Hyderabad",
  "pais": "India",
  "salario": 4200,
  "edad": 70,
  "altura": 160,
  "peso": 140
  },
  {
  "nombres": "Raj",
  "apellidos": "Singh",
  "correo": "ejemplo@riwi.io",
  "ciudad": "Chennai",
  "pais": "India",
  "salario": 4000,
  "edad": 65,
  "altura": 175,
  "peso": 165
  },
  {
  "nombres": "Priya",
  "apellidos": "Shah",
  "correo": "borrar@riwi.io",
  "ciudad": "Bello",
  "pais": "India",
  "salario": 4300,
  "edad": 70,
  "altura": 158,
  "peso": 145
  },
  {
  "nombres": "Sanjay",
  "apellidos": "Verma",
  "correo": "ejemplo@riwi.io",
  "ciudad": "Pune",
  "pais": "India",
  "salario": 3800,
  "edad": 65,
  "altura": 170,
  "peso": 160
  },
  {
  "nombres": "Rita",
  "apellidos": "Naidu",
  "correo": "borrar@riwi.io",
  "ciudad": "Ahmedabad",
  "pais": "India",
  "salario": 4200,
  "edad": 70,
  "altura": 165,
  "peso": 150
  },
  {
  "nombres": "Arun",
  "apellidos": "Iyer",
  "correo": "ejemplo@riwi.io",
  "ciudad": "Jaipur",
  "pais": "India",
  "salario": 4100,
  "edad": 65,
  "altura": 168,
  "peso": 155
  },
  {
  "nombres": "Sunita",
  "apellidos": "Menon",
  "correo": "borrar@riwi.io",
  "ciudad": "Lucknow",
  "pais": "India",
  "salario": 4400,
  "edad": 70,
  "altura": 162,
  "peso": 140
  },
  {
  "nombres": "Deepak",
  "apellidos": "Rajput",
  "correo": "ejemplo@riwi.io",
  "ciudad": "Surat",
  "pais": "India",
  "salario": 3900,
  "edad": 65,
  "altura": 173,
  "peso": 165
  },
  {
  "nombres": "Asha",
  "apellidos": "Kulkarni",
  "correo": "borrar@riwi.io",
  "ciudad": "Nagpur",
  "pais": "India",
  "salario": 4300,
  "edad": 70,
  "altura": 166,
  "peso": 155
  },
  {
  "nombres": "Vikram",
  "apellidos": "Joshi",
  "correo": "ejemplo@riwi.io",
  "ciudad": "Indore",
  "pais": "India",
  "salario": 4200,
  "edad": 65,
  "altura": 176,
  "peso": 160
  },
  {
  "nombres": "Takashi",
  "apellidos": "Sato",
  "correo": "ejemplo@riwi.io",
  "ciudad": "Tokyo",
  "pais": "Japón",
  "salario": 4500,
  "edad": 65,
  "altura": 170,
  "peso": 160
  },
  {
  "nombres": "Yuko",
  "apellidos": "Tanaka",
  "correo": "borrar@riwi.io",
  "ciudad": "Osaka",
  "pais": "Japón",
  "salario": 4700,
  "edad": 70,
  "altura": 165,
  "peso": 150
  },
  {
  "nombres": "Hiroshi",
  "apellidos": "Suzuki",
  "correo": "ejemplo@riwi.io",
  "ciudad": "Nagoya",
  "pais": "Japón",
  "salario": 4300,
  "edad": 65,
  "altura": 175,
  "peso": 155
  },
  {
  "nombres": "Sakura",
  "apellidos": "Kobayashi",
  "correo": "borrar@riwi.io",
  "ciudad": "Sapporo",
  "pais": "Japón",
  "salario": 4700,
  "edad": 70,
  "altura": 160,
  "peso": 140
  },
  {
  "nombres": "Daichi",
  "apellidos": "Yamamoto",
  "correo": "ejemplo@riwi.io",
  "ciudad": "Fukuoka",
  "pais": "Japón",
  "salario": 4500,
  "edad": 65,
  "altura": 180,
  "peso": 165
  },
  {
  "nombres": "Nao",
  "apellidos": "Nakamura",
  "correo": "borrar@riwi.io",
  "ciudad": "Kobe",
  "pais": "Japón",
  "salario": 4800,
  "edad": 70,
  "altura": 158,
  "peso": 145
  },
  {
  "nombres": "Hikaru",
  "apellidos": "Matsui",
  "correo": "ejemplo@riwi.io",
  "ciudad": "Kyoto",
  "pais": "Japón",
  "salario": 4300,
  "edad": 65,
  "altura": 170,
  "peso": 160
  },
  {
  "nombres": "Noboru",
  "apellidos": "Kato",
  "correo": "borrar@riwi.io",
  "ciudad": "Hiroshima",
  "pais": "Japón",
  "salario": 4700,
  "edad": 70,
  "altura": 165,
  "peso": 150
  },
  {
  "nombres": "Kyoko",
  "apellidos": "Sasaki",
  "correo": "ejemplo@riwi.io",
  "ciudad": "Sendai",
  "pais": "Japón",
  "salario": 4600,
  "edad": 65,
  "altura": 175,
  "peso": 155
  },
  {
  "nombres": "Tetsuya",
  "apellidos": "Ito",
  "correo": "borrar@riwi.io",
  "ciudad": "Chiba",
  "pais": "Japón",
  "salario": 4900,
  "edad": 70,
  "altura": 160,
  "peso": 140
  },
  {
  "nombres": "Aiko",
  "apellidos": "Takahashi",
  "correo": "ejemplo@riwi.io",
  "ciudad": "Yokohama",
  "pais": "Japón",
  "salario": 4400,
  "edad": 65,
  "altura": 180,
  "peso": 165
  },
  {
  "nombres": "Shinji",
  "apellidos": "Saito",
  "correo": "borrar@riwi.io",
  "ciudad": "Kawasaki",
  "pais": "Japón",
  "salario": 4800,
  "edad": 70,
  "altura": 158,
  "peso": 145
  },
  {
  "nombres": "Mayumi",
  "apellidos": "Watanabe",
  "correo": "ejemplo@riwi.io",
  "ciudad": "Tokyo",
  "pais": "Japón",
  "salario": 4500,
  "edad": 65,
  "altura": 170,
  "peso": 160
  },
]
)

db.base_datos_empleados.insertMany(
  [
  ]
)